<?php
 // Hui.admin v1.0 系统生成网站配置文件
 return [
	'keywords' => 'Hui.admin',
	'describle' => 'Hui.admin',
	'status' => 1,
	'stopinfo' => '网站系统正在努力建设中，请稍后访问......',
	'siteurl' => 'http://127.0.0.4',
	'email' => '952612251@qq.com',
	'sitetime' => '2017-1-1',
	'clearcache' => 3,
	'codeset' => '123456abc',
	'mailer_host' => 'smtp.qq.com',
	'mailer_char' => 'UTF-8',
	'mailer_port' => 465,
	'mailer_secure' => 'ssl',
	'mailer_username' => '952612251@qq.com',
	'mailer_password' => 'vzyyflbdpmfobcfd',
	'mailer_from_email' => '952612251@qq.com',
	'mailer_from_name' => 'Hui.admin系统邮件',
	'mailer_reply_email' => '952612251@qq.com',
	'mailer_reply_name' => 'Hui.admin系统邮件',
	'sitename' => 'Hui.admin',
	'codelength' => 3,
	'is_upload' => 1,
	'photodir' => 'images',
	'photosize' => 2097152,
	'photoext' => 'png,jpg,jpeg,bmp,gif',
	'logs' => 1,
	'swftools' => 'F:\SWFTools\pdf2swf.exe',
	'backup_dir' => 'backup',
	'export_dir' => 'export',
	'convert_dir' => 'convert',
	'office_dir' => 'office',
	'photo_dir' => 'images',
	'video_dir' => 'video',
	'attach_dir' => 'attach',
];